services:
  planne-live-code:
    # Set the container name
    container_name: planne-live-code

    # set name for the image
    image: planne-live-code

    # Build the image using the Dockerfile in the current context
    build:
      context: .
      dockerfile: Dockerfile

    # Map host port 5173 to container port 5173
    ports:
      - "5173:5173" #<host_port>:<container_port/protocol_port>

    # Mount the current directory to /app in the container
    volumes:
      - .:/app

    # Specify the command to run when the container starts
    command: npm run dev
